---
title: "Amazon Analysis"
output:
  html_notebook:
    df_print: kable
---


From https://www.wsj.com/market-data/quotes/AMZN/financials/annual/income-statement

Analyze revenue growth
```{r}
year <- c(2018, 2019, 2020, 2021, 2022)
revenue <- c(232887, 280522, 386064, 469822, 513983)

plot_height <- signif(revenue/1000, digits = 3)
barplot(plot_height, names.arg = year, main = 'Amazon.com Sales/Revenue', xlab = 'Year', ylab = "Billion Dollars")
```

```{r}
r <- length(year)
revenue_data <- data.frame(revenue)
rownames(revenue_data) <- year

revenue_data$growth <- NA
revenue_data$growth[2:r] <- diff(revenue_data$revenue)

revenue_data$growth_rate <-NA
revenue_data$growth_rate[2:r] <- revenue_data$growth[2:r] / revenue_data$revenue[1:r-1]

print(signif(revenue_data, digits = 3))
agr <- mean(revenue_data$growth_rate)
```

In this section we calculate the net operating profit (NOP) and neta operating profit margin (NOPM).
The formula is:
$$NOP=Revenue-({CGS}+{SGA}+{R\&D})$$
and
$$NOPM=NOP/{OperatingRevenue}$$
Cost of Goods Sold (CGS), Selling, General and Administrative Expenses (SGA), Research and Development (RND). Operating revenue is revenue generated by the company's primary business operations.

```{r}
cgs <- c(123815, 143747, 208056, 238048, 246910)
sga <- c(52177, 64313, 87193, 116485, 138428)
rnd <- c(28837, 35931, 42740, 56052, 73213)
nop <- revenue -(cgs + sga + rnd)
nopm <- nop / revenue
nopm_data <- data.frame(revenue,cgs,sga,rnd,nop,nopm)
rownames(nopm_data) <- year
print(signif(nopm_data, digits = 3))
```